TOPIC_CONVEYOR_COMMAND = "conveyor/command"
TOPIC_CONVEYOR_SERVO = "conveyor/servo"
TOPIC_CONVEYOR_STATUS = "conveyor/status"
TOPIC_CONVEYOR_HEARTBEAT = "conveyor/heartbeat"

SUBSCRIBE_TOPICS = [
    (TOPIC_CONVEYOR_COMMAND, 1),
    (TOPIC_CONVEYOR_SERVO, 1),
    (TOPIC_CONVEYOR_STATUS, 0),
    (TOPIC_CONVEYOR_HEARTBEAT, 0),
]
