# Generated by Django 5.0.6 on 2026-03-23 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=50, unique=True)),
                ('servo_angle', models.IntegerField()),
                ('color_hex', models.CharField(max_length=7)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grade_configs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConveyorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('error', 'Error')], default='running', max_length=20)),
                ('total_count', models.IntegerField(default=0)),
                ('whole_count', models.IntegerField(default=0)),
                ('splitup_count', models.IntegerField(default=0)),
                ('splitdown_count', models.IntegerField(default=0)),
                ('broken_count', models.IntegerField(default=0)),
                ('defect_count', models.IntegerField(default=0)),
                ('conveyor_speed', models.FloatField(default=0)),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_sessions', to='dashboard.appuser')),
            ],
            options={
                'db_table': 'conveyor_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='conveyor.conveyorsession')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassifyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('servo_angle', models.IntegerField()),
                ('delay_ms', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classify_results', to='conveyor.conveyorsession')),
                ('grade_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='conveyor.gradeconfig')),
            ],
            options={
                'db_table': 'classify_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
